Glassa/Controllers/GlassController.cs
using Database;
using Database.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Glassa.Models;
using System.IO;

namespace Glassa.Controllers
{
    public class GlassController : Controller
    {
        private GlassDBContext db = new GlassDBContext();

        // GET: Glass
        public ActionResult Index()
        {
            ViewBag.all = db.Glassar.Count();
            ViewBag.tasted = db.Glassar.Count(g => g.Tasted == true);
            
            return View(db.Glassar.OrderByDescending(g => g.ID).ToList());
        }

        // GET: Glass/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Glass glass = db.Glassar.Find(id);
            if (glass == null)
            {
                return HttpNotFound();
            }
            return View(glass);
        }

        // GET: Glass/Create
        public ActionResult Create()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index");
            }  
 
            return View();
        }

        // POST: Glass/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price,Maker,Picture,Tasted")] Glass glass, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                Picture(glass, imageFile);
                db.Glassar.Add(glass);
                db.SaveChanges();

                ViewBag.Message = "Glassen lades till!";
                return RedirectToAction("Index");
            }

            return View(glass);
        }

        // GET: Glass/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index");
            }  
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Glass glass = db.Glassar.Find(id);
            if (glass == null)
            {
                return HttpNotFound();
            }
            return View(glass);
        }

        // POST: Glass/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price,Maker,Picture,Tasted")] Glass glass, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(glass).State = EntityState.Modified;
                Picture(glass, imageFile);
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(glass);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Tasted(int id)
        {
            Glass glass = db.Glassar.Find(id);
            if (glass.Tasted == false) glass.Tasted = true;
            else glass.Tasted = false;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public void Picture(Glass glass, HttpPostedFileBase imageFile)
        {
            var path = String.Empty;
            if (imageFile != null && imageFile.ContentLength > 0)
            {
                var fileName = glass.Name + "_" + Path.GetFileName(imageFile.FileName);
                var filePath = Path.Combine(Server.MapPath("~/Content/Images"), fileName);

                try
                {
                    imageFile.SaveAs(filePath);
                    path = String.Format("/Content/Images/{0}", fileName);
                }
                catch (Exception e)
                { }

               glass.Picture = path;
            }
        }

    

        // GET: Glass/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index");
            }  
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Glass glass = db.Glassar.Find(id);
            if (glass == null)
            {
                return HttpNotFound();
            }
            return View(glass);
        }

        // POST: Glass/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Glass glass = db.Glassar.Find(id);
            db.Glassar.Remove(glass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Glassa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Glassa</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Glassa", "Index", "Glass", new { area = "" }, new { @class = "navbar-brand" })
                
            </div>
            
            <div class="navbar-collapse collapse">
                           
               @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <br /><br /><br /><br />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>